CELL_SIZE = 40
CELL_NUMS = 20

SCREEN_WIDTH, SCREEN_HEIGHT = (CELL_SIZE * CELL_NUMS), (CELL_SIZE * CELL_NUMS)

PYGAME_CAPTION = "snek gam"
ICON = "" #THIS WILL BE A 32x32 .png

FPS = 60

MEANING_OF_LIFE_UNIVERSE_AND_EVERYTHING = 42